/**
 * Workflow class managing inner Tabs
 * @class Workflow
 */
function Workflow(tempJson, id, fx, fy, tx, ty, colored){
    this.ID;
    this.fx;
    this.fy;
    this.tx;
    this.ty;
    this.name;
    this.tabsIds;
    this.tabs;
    this.selectedTab;
}
/**
 * Get Array Diffrenece helper function
 * @param  {Array} before 
 * @param  {Array} after
 */
Workflow.getDiffArrays = function(before,after) {}

Workflow.prototype = {

    /**
     * Update current object with new content
     * @param  {object} tempJson Workflow object generated by toJson method
     */
    updateAllParams:  function(tempJson, colored){},

    /**
     * Override "==" operator to compare between object <br>Return True if two objects are equals
     * @param  {object} obj Workflow object
     */
    equals: function(obj){},

    /**
     * Initialize new Tab object and push it to workflow tabs array
     */
    addTab: function(){},

    /**
     * Scrolls to a specific location on the screen.
     */
    scrollTo: function(){},

    /**
     * Gets the position of the Workflow<br> Return The position if the Workflow
     */
    getPosition: function(){},

    /**
     * Override toString default function to return json stringify<br> Return Json stringify string
     */
    toString: function(){},

    /**
     * Creates Json <br> Return Json object
     */
    toJson:function(){},

    selectTab: function(workflow, tab) {},
    toJsonSteps: function(){},
    getSelectedTabIndex: function(workflow){},
    closeTab: function(workflow){}
};
