/**
 * Workflow class managing inner Tabs
 * @class Workflow
 * @constructor
 * @param {JSON} tempJson
 * @param {Number} id      
 * @param {Number} fx      
 * @param {Number} fy      
 * @param {Number} tx      
 * @param {Number} ty      
 * @param {Boolean} colored 
 */
function Workflow(tempJson, id, fx, fy, tx, ty, colored){
    /**
     * Holding workflow id
     * @protected Workflow
     */
    this.ID;
    /**
     * Holding workflow starting index x
     * @protected Workflow
     */
    this.fx;
    /**
     * Holding workflow starting index y
     * @protected Workflow
     */
    this.fy;
    /**
     * Holding workflow ending index x
     * @protected Workflow
     */
    this.tx;
    /**
     * Holding workflow ending index y
     * @protected Workflow
     */
    this.ty;
    /**
     * Holding workflow name
     * @protected Workflow
     */
    this.name;
    /**
     * Holding workflow tabs ID
     * @protected Workflow
     */
    this.tabsIds;
    /**
     * Holding workflow tabs
     * @protected Workflow
     */
    this.tabs;
    /**
     * Holding workflow selected tab
     * @protected Workflow
     */
    this.selectedTab;
}
/**
 * Get Array Diffrenece helper function
 * @param  {Array} before 
 * @param  {Array} after
 * @public
 */
Workflow.getDiffArrays = function(before,after) {}

Workflow.prototype = {

    /**
     * Update current object with new content
     * @param  {object} tempJson Workflow object generated by toJson method
     */
    /**
     * Update current object with new content  
     * @param  {Object} tempJson 
     * @param  {Boolean} colored 
     */
    updateAllParams:  function(tempJson, colored){},

    /**
     * Override "==" operator to compare between object <br><b>Return</b> True if two objects are equals
     * @param  {object} obj Workflow object
     */
    equals: function(obj){},

    /**
     * Initialize new Tab object and push it to workflow tabs array
     */
    addTab: function(){},

    /**
     * Scrolls to a specific location on the screen.
     */
    scrollTo: function(){},

    /**
     * Gets the position of the Workflow<br> <b>Return</b> The position if the Workflow
     */
    getPosition: function(){},

    /**
     * Override toString default function to return json stringify<br> <b>Return</b> Json stringify string
     */
    toString: function(){},

    /**
     * Creates Json <br> <b>Return</b> Json object
     */
    toJson:function(){},

    /**
     * Modify corrent selected tab
     * @param  {Tab} tab  
     */
    selectTab: function(tab) {},
    
    /**
     * Creates Json Steps <br> <b>Return</b> Json object
     */
    toJsonSteps: function(){},

    /**
     * Gets the selected tab index <br> <b>Returns</b> selected tab index
     * @param  {Object} workflow
     */
    getSelectedTabIndex: function(workflow){},

    /**
     * Close specific tab
     * @param  {Object} workflow
     */
    closeTab: function(workflow){}
};
